### ISSUE TITLE
Unable to marshall object of type io.github.bucket4j.local.LockFreeBucket

### ISSUE THREAD

**Issue by tirumaleshYeligar** [bucket4j/bucket4j#493] opened 2024-05-23 16:30 UTC
Hi,

Needed an help I'm trying to use infispan with bucket4j below is my piece of code bascially i'm trying to build the ratelimiter using the below logic

 public boolean isRateLimited(String key) {
        Bucket bucket = cacheManager.getCache("rate-limiter").get(key, Bucket.class);
        if (bucket == null) {
            bucket = bucketSupplier.get();
            Cache cache = cacheManager.getCache("rate-limiter");
            cache.put(key, bucket);
        }
        return !bucket.tryConsume(1);
    } 

When it tries to put the key i.e  cache.put(key, bucket)  I'm getting exception as org.infinispan.client.hotrod.exceptions.HotRodClientException:: Unable to marshall object of type [io.github.bucket4j.local.LockFreeBucket]] with root cause

java.io.NotSerializableException: io.github.bucket4j.local.LockFreeBucket
And below is my RemoteCacheManagerConfiugration 

 @Bean
    public RemoteCacheManager getRemoteCacheManager() {

        ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();

    configurationBuilder
        .addServer()
        .host("somehost")
        .port(11222)
        .marshaller(new JavaSerializationMarshaller())
        .addJavaSerialWhiteList("io.github.bucket4j.*")
        .security()
        .ssl()
        .sniHostName("infinispan")
        .trustStoreFileName("./cacerts 2")
        .trustStorePassword("changeit".toCharArray())
        .authentication()
        .username("some")
        .password("somepassword")
        .addContextInitializer(new CreateProtoImpl())
        .clientIntelligence(ClientIntelligence.BASIC);
        return new RemoteCacheManager(configurationBuilder.build());
    }

**Comment by vladimir-bukhtoyarov** [comment] 2024-05-23 18:17
Hello @tirumaleshYeligar 

You should to use direct integration with Infinispan https://bucket4j.com/8.12.1/toc.html#bucket4j-infinispan

**Comment by tirumaleshYeligar** [comment] 2024-05-23 19:17
@vladimir-bukhtoyarov still I'm facing the same issue Can you please check my pom.xml for dependencies any mismatch in the versions
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>spring-boot-2-hello-world</artifactId>
    <version>1.0.2-SNAPSHOT</version>

    <name>spring-boot-2-hello-world</name>
    <description>A simple Spring Boot 2.x app to send hello world message to a user</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>



            
        <dependency>
            <groupId>com.github.vladimir-bukhtoyarov</groupId>
            <artifactId>bucket4j-core</artifactId>
            <version>7.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.bucket4j</groupId>
            <artifactId>bucket4j_jdk17-infinispan</artifactId>
            <version>8.12.1</version>
        </dependency>


        
            <dependency>
                <groupId>org.infinispan</groupId>
                <artifactId>infinispan-spring-boot-starter-remote</artifactId>
                <version>13.0.0.Final</version>
            </dependency>


        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-api</artifactId>
            <version>14.0.4.Final</version>
            <scope>compile</scope>
        </dependency>
        

        
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-cache</artifactId>
            </dependency>


    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>15</source>
                    <target>15</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

And below is my CacheConfig

 @Bean
    public RemoteCacheManager getRemoteCacheManager() {

        ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();

    configurationBuilder
        .addServer()
        .host("addss")
        .port(11222)
        .marshaller(new JavaSerializationMarshaller())
        .addJavaSerialWhiteList("io.github.bucket4j.*")
        .security()
        .ssl()
        .sniHostName("infinispan")
        .trustStoreFileName("./cacerts 2")
        .trustStorePassword("changeit".toCharArray())
        .authentication()
        .username("fs")
        .password("fd")
        .addContextInitializer(new Bucket4jProtobufContextInitializer())
        .clientIntelligence(ClientIntelligence.BASIC);
        return new RemoteCacheManager(configurationBuilder.build());
    }

**Comment by tirumaleshYeligar** [comment] 2024-05-23 19:19
This is the exception I'm getting currently

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.infinispan.client.hotrod.exceptions.HotRodClientException:: Unable to marshall object of type [io.github.bucket4j.local.LockFreeBucket]] with root cause

java.io.NotSerializableException: io.github.bucket4j.local.LockFreeBucket

**Comment by vladimir-bukhtoyarov** [comment] 2024-05-23 19:43
@vladimir-bukhtoyarov 

As I have mentioneed above, you should not try to persist anything in Infinispan by yourself, because this way leads to problems related to data races. Read this example https://bucket4j.com/8.12.1/toc.html#example-1-limiting-access-to-http-server-by-ip-address that shows how to use ProxyManager, and then write something similar using bucket4j-infinispan.

**Comment by tirumaleshYeligar** [comment] 2024-05-24 05:03
@vladimir-bukhtoyarov I have created proxy manger but it is working with embedded mangaer that it is working as a local cache but I want to connect to remote cache please help below is my code and also I have remoteCacheManager method is read as posted in the first comment
@Configuration
public class InfinispanConfig {

    @Bean
    public EmbeddedCacheManager cacheManager() {
        GlobalConfigurationBuilder globalConfig = new GlobalConfigurationBuilder().nonClusteredDefault().defaultCacheName("defaultCache");
        ConfigurationBuilder config = new ConfigurationBuilder();
        config.memory().storageType(StorageType.HEAP);
        EmbeddedCacheManager cacheManager = new DefaultCacheManager(globalConfig.build(), config.build());
        cacheManager.defineConfiguration("rate-limit-bucket", config.build());
        cacheManager.getCache("rate-limit-bucket"); // ensure cache is created
        return cacheManager;
    }
    
   
    @Bean
    public Supplier<BucketConfiguration> bucketConfiguration() {
        Refill refill = Refill.intervally(200, Duration.ofMinutes(1));
        return () -> BucketConfiguration.builder()
                .addLimit(Bandwidth.classic(200L, refill))
                .build();
    }

    private static FunctionalMap.ReadWriteMap toMap(EmbeddedCacheManager cm) {
        org.infinispan.Cache nativeCache = cm.getCache("rate-limit-bucket");
        FunctionalMapImpl functionalMap = FunctionalMapImpl.create(nativeCache.getAdvancedCache());
        return ReadWriteMapImpl.create(functionalMap);
    }

    @Bean
    public ProxyManager<String> infinispanProxyManager() {
        return new InfinispanProxyManager<>(toMap(cacheManager()));
    }

**Comment by tirumaleshYeligar** [comment] 2024-05-24 05:05
@vladimir-bukhtoyarov And this is how I'm using ProxyManager 
 public boolean isRateLimited(String key) {
        var bucket = proxyManager.getProxyConfiguration(key);
        if (bucket.isEmpty()) {
            var bucket1 = bucketConfigurationSupplier.get();
            proxyManager.builder().build(key, bucket1).getOptimizationController().syncImmediately();
        }
        return false;
        }
}

**Comment by vladimir-bukhtoyarov** [comment] 2024-05-24 06:14
> I have created proxy manger but it is working with embedded manager it is working as a local cache but I want to connect to remote cache please help..

The question is out of scope for Bucket4j. You need to go directly to Infinispan documentation(or forum), and consult about how to create ReadWriteMapImpl for your deployment topology.

> And this is how I'm using ProxyManager

I do not understand what does `isRateLimited` method should do. What is a goal of this method?

**Comment by tirumaleshYeligar** [comment] 2024-05-24 06:40
@vladimir-bukhtoyarov  isRateLimited method takes key as an a input and checks in the bucket if token are left in the bucket it returns true or false this is what my main idea but it is partially implemented

**Comment by vladimir-bukhtoyarov** [comment] 2024-05-24 10:38
> @vladimir-bukhtoyarov isRateLimited method takes key as an a input and checks in the bucket if token are left in the bucket it returns true or false this is what my main idea but it is partially implemented

You should rewrite like this:
```java
public boolean isRateLimited(String key) {
       Bucket bucket = proxyManager.getProxy(key, () -> bucketConfiguration);
       return !bucket.tryConsume(1);
  }
}
```

**Comment by tirumaleshYeligar** [comment] 2024-05-25 01:42
@vladimir-bukhtoyarov not able to create InfinispanProxyManager with remote cluster details checkedw with infispan but no luck could you please help how can i create proxymanager and use above your code seems to be infispan community is dead...https://github.com/bucket4j/bucket4j/blob/master/bucket4j-infinispan-all/bucket4j-infinispan/src/main/java/io/github/bucket4j/grid/infinispan/InfinispanProxyManager.java

**Comment by vladimir-bukhtoyarov** [comment] 2024-05-25 18:10
After quick discovering of [Hot Road Client documentation](https://infinispan.org/docs/13.0.x/titles/hotrod_java/hotrod_java.html) I have released that RemoteCacheManager/RemoteCache do not support ReadWriteMap, so `bucket4j-infinispan` integration can not be used with it as is. I have created dedicate issue #495 to add support for Infinispan Hotroad.The ETA of #495 is not defined, usually I prefer to avoid doing something for opensource at summer.

According to initial question from which this thread is started:
* You need to store just a array of bytes in RemoteCache.
* Use [toBinarySnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L61) when it needs to convert LocalBucket to array of bytes.
* Use [fromBinarySnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L71) when it needs to reconstruct the LocalBucket from array of bytes.
* And, it is obviosly that you need to introduce some transactional/locking code, in order to prevent missed updates caused by dataraces. I wish you good luck to understand and configure Hot Road transaction [according to this documentation](https://infinispan.org/docs/13.0.x/titles/hotrod_java/hotrod_java.html#hotrod_transactions).

**Comment by FuncGuy** [comment] 2024-05-26 08:13
@vladimir-bukhtoyarov 
![Namskara](https://github.com/bucket4j/bucket4j/assets/49618191/8dac6662-2555-407e-a353-189c10aadb6b)

**Closed** 2024-06-01 08:48 UTC
Labels: question

**Comment by vladimir-bukhtoyarov** [comment] 2024-06-07 13:28
@FuncGuy @tirumaleshYeligar 

Since `8.13.0` you can use direct support for Infinispan RemoteCache(Hot Rod client) as described there https://bucket4j.com/8.13.0/toc.html#example-of-bucket-instantiation-for-remotecachemanagerhot-rod-client
