### ISSUE TITLE
Jedis-based reconfiguration not working properly with RESET and ADDITIVE strategies

### ISSUE THREAD

**Issue by aldobongio** [bucket4j/bucket4j#419] opened 2023-11-02 16:14 UTC
I think I've found an issue with two reconfiguration strategies using the Jedis-based bucket. I'm using the newest 8.6.0 release.
I used a very simple test which configures a Bucket with 5 permissions / min, tests it, reconfigures the bucket with 10 permissions /min, wait 1 minute in order to let the tokens to be refilled, and re-tests it. All is repeated for each `TokensInheritanceStrategy`, with a brand new Bucket at each iteration.

To reproduce the issue you can use the following gists:

1. Starting from [LocalSnippet.java](https://gist.github.com/aldobongio/90be9ad345b742eb4cc59668661eabd5), adding a `main `and invoking `test()`, you can see a local bucket correctly working. The output is in [local-output.txt](https://gist.github.com/aldobongio/116b298343249dd4b89944694847570f)
2. Starting from [JedisSnippet.java](https://gist.github.com/aldobongio/dc81a29200eb0e92b63a9dc945e8868c) and extending it a bit in order to send a `JedisBasedProxyManager `to the `test` method, the output you obtain is shown in [jedis-output.txt](https://gist.github.com/aldobongio/f4811bddd38043c7c592817ab397be16). The `ADDITIVE `and `RESET `reconfiguration are not working as expected: after the reconfiguration and after the one-minute delay the expected rate of 10/min is not obtained.

**Comment by vladimir-bukhtoyarov** [comment] 2023-11-02 18:40
I am unable to reproduce. See releated commit https://github.com/bucket4j/bucket4j/commit/14dbfe7b192e41d2b4eb7194970038c7fb24ed22

What is TTL? If TTL is small the following case can happen:
* Bucket became expired after long slleeping after configuration replacement. 
* When trying consume after sleep,  bucket is being recreated with previos configuration because configuration supplier always returns the same configuration.

**Comment by aldobongio** [comment] 2023-11-02 19:51
Ok, I just changed my codebase in order to use a really dynamic `Supplier<BucketConfiguration>`, which adapts to the changes on the rate. So when `Bucket::replaceConfiguration` is invoked with the `Supplier::get` result as argument, at the same time, if the bucket became expired as in your scenario, the same `Supplier::get` is invoked internally, giving the correct behaviour.

I just wonder if the proxy manager non-deprecated `build` method and/or the bucket `replaceConfiguration` methods should be annotated in their Javadoc with the specific scenario we just encountered in order to help developers when a reconfiguration is needed.

**Comment by vladimir-bukhtoyarov** [comment] 2023-11-02 20:01
Ok, now I can explain the output.

## strategy=RESET
After configuration replacement bucket is full, so TTL at replacement calculated as keepAfterRefillDuration(10 seconds).
Bucket had been already expired when you tried to consume after sleep, so it was ressurected from configuration supplier.

## strategy=ADITIVE
After configuration replacement bucket will contain 5 tokens, it needs 30 seconds for full refill, so TTL at replacement calculated as 30 + 10 = 40 seconds, which is less than 60 seconds.
Bucket had been already expired when you tried to consume after sleep, so it was ressurected from configuration supplier.

**Comment by vladimir-bukhtoyarov** [comment] 2023-11-02 20:10
To avoid such situations you always need to return actual configuration from supplier. I have updated the test according to your expiration strategy, and updated the supplier, test passes.

**Comment by vladimir-bukhtoyarov** [comment] 2023-11-02 20:18
> I just wonder if the proxy manager non-deprecated `build` method and/or the bucket `replaceConfiguration` methods should be annotated in their Javadoc with the specific scenario we just encountered in order to help developers when a reconfiguration is needed.

Yes, I will add more docs. Scenario that we are discussing today was a cause of deprication [this](https://github.com/bucket4j/bucket4j/blob/8.6/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/RemoteAsyncBucketBuilder.java#L98) and [this](https://github.com/bucket4j/bucket4j/blob/8.6/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/RemoteBucketBuilder.java#L114). But, I was wrong when thought that deprecation was enough, the documentation is still uncomplete and will be fixed in next releases.

**Closed by vladimir-bukhtoyarov** 2023-11-02 20:18 UTC
